#
###################################
# Site wide configuration
####################################
#
title:       "blog.isaack.io"
description: "Tools, ideas on infrustrcuture architecture for application delivery"
url:         https://blog.isaack.io//
enforce_ssl: blog.isaack.io/

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          redcarpet
#highlighter:       rouge
#excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

# kramdown:
#   auto_ids:       true
#   footnote_nr:    1
#   entity_output:  as_char
#   toc_levels:     1..6
#   enable_coderay: false
#   input: GFM

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Isaack Karanja
  avatar: avatar.jpg
  job: "Cloud Solutions Architect"
  bio: "I specialize in the building of infrustucture to run large scale applications"
  twitter: fvtool
  google:
    plus:
    analytics:
  github: mugithi
  linkedin: isaackkaranja

